import Head from 'next/head'

import { Heading } from 'common/Heading';

export default function Register() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading as="h1">dit is de register pageeeeeee</Heading>
    </div>
  )
}